export const currencyOptions = [
  { value: 'AUD', text: 'Australian Dollar' },
  { value: 'BGN', text: 'Bulgarian Lev' },
  { value: 'BRL', text: 'Brazilian Real' },
  { value: 'GBP', text: 'British Pound Sterling' },
  { value: 'CAD', text: 'Canadian Dollar' },
  { value: 'CNY', text: 'Chinese Yuan' },
  { value: 'HRK', text: 'Croatian Kuna' },
  { value: 'CZK', text: 'Czech Republic Koruna' },
  { value: 'DKK', text: 'Danish Krone' },
  { value: 'EUR', text: 'Euro' },
  { value: 'HKD', text: 'Hong Kong Dollar' },
  { value: 'HUF', text: 'Hungarian Forint' },
  { value: 'ISK', text: 'Icelandic Króna' },
  { value: 'INR', text: 'Indian Rupee' },
  { value: 'IDR', text: 'Indonesian Rupiah' },
  { value: 'ILS', text: 'Israeli New Sheqel' },
  { value: 'JPY', text: 'Japanese Yen' },
  { value: 'KRW', text: 'South Korean Won' },
  { value: 'MYR', text: 'Malaysian Ringgit' },
  { value: 'MXN', text: 'Mexican Peso' },
  { value: 'NZD', text: 'New Zealand Dollar' },
  { value: 'NOK', text: 'Norwegian Krone' },
  { value: 'PHP', text: 'Philippine Peso' },
  { value: 'PLN', text: 'Polish Zloty' },
  { value: 'RON', text: 'Romanian Leu' },
  { value: 'RUB', text: 'Russian Ruble' },
  { value: 'ZAR', text: 'South African Rand' },
  { value: 'SGD', text: 'Singapore Dollar' },
  { value: 'SEK', text: 'Swedish Krona' },
  { value: 'CHF', text: 'Swiss Franc' },
  { value: 'THB', text: 'Thai Baht' },
  { value: 'TRY', text: 'Turkish Lira' },
  { value: 'USD', text: 'US Dollar' },
];